#!/bin/bash
# postrm script for libserial
# This script runs after the package is removed

set -e

case "$1" in
    remove|purge)
        # Update the shared library cache
        ldconfig
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
